# Data
dataset: 'squad-split2'
pre_word_emb_file: '/Users/hugo/Documents/Work/Research/Resources/glove-vectors/glove.840B.300d.txt' # path to the pretrained word embedding file
out_dir: 'out/squad_split2/ggnn_bi_fuse_constituency_ckpt'

# Preprocessing
top_word_vocab: 70000
share_vocab: True
word_emb_size: 300
min_word_freq: 1
num_hidden: 300 # number of hidden units
n_samples: 50


word_dropout: 0.4 # word embedding dropout
enc_rnn_dropout: 0.3 # Encoder RNN dropout
coverage_loss_ratio: 0.3 # coverage loss ratio


# Training
seed: 1234
batch_size: 50 # batch size
epochs: 1 # number of maximal training epochs
grad_clipping: 10
early_stop_metric: 'BLEU_4'
patience: 10
lr: 0.001 # learning rate
lr_patience: 2
lr_reduce_factor: 0.5
num_workers: 2 # number of data loader workers


# Beam search
beam_size: 2

gpu: -1
no_cuda: false
