topology_type: 'dependency'
graph_type: 'static'
root_dir: "graph4nlp/pytorch/test/dataset/jobs"
topology_subdir: 'DependencyGraph'
edge_strategy: 'homogeneous'
merge_strategy: 'tailhead'
dynamic_graph_type: null
init_graph_type: null
share_vocab: True
