graph_construction_name: "kg"
graph_embedding_name: "ggnn"
decoder_name: "distmult"
out_dir: "out/kgc/wn18rr/ggnn_uni_ckpt"
model_type: 'ggnn'

vocab_lower_case: true

graph_construction_args:
  graph_construction_share:
    root_dir: 'examples/pytorch/kg_completion/WN18RR'
    topology_subdir: 'e1rel_to_e2'

  graph_construction_private:
    edge_strategy: null # None or "as_node"

  node_embedding:
    input_size: 300
    hidden_size: 300
    word_dropout: 0.2
    rnn_dropout: 0.3
    fix_bert_emb: false
    fix_word_emb: false
    embedding_style:
      single_token_item: false
      emb_strategy: "w2v_bilstm"
      num_rnn_layers: 1
      bert_model_name: null
      bert_lower_case: null

graph_embedding_args:
  graph_embedding_share:
    num_layers: 2
#    input_size: 300
    hidden_size: 300
#    output_size: 300
    direction_option: "undirected"
#    feat_drop: 0.2

  graph_embedding_private:
    ggnn_norm: 'both'
    weight: true
    bias: true
    activation: null
    allow_zero_in_degree: false
    use_edge_weight: false

decoder_args:
