graph_construction_share:
  graph_type: 'node_emb'
  root_dir: null
  topology_subdir: 'NodeEmbGraph'

graph_construction_private:
  lower_case: false

node_embedding:
  hidden_size: 300
  word_dropout: 0.0
  rnn_dropout: 0.0
  fix_bert_emb: false
  fix_word_emb: false
  embedding_style:
    single_token_item: true
    emb_strategy: "w2v_bilstm"
    num_rnn_layers: 1
    bert_model_name: null
    bert_lower_case: null

  sim_metric_type: 'weighted_cosine'
  num_heads: 1
  top_k_neigh: null,
  epsilon_neigh: 0.5
  smoothness_ratio: 0.1
  connectivity_ratio: 0.05
  sparsity_ratio: 0.1
