graph_construction_name: "kg"
graph_embedding_name: "graphsage"
decoder_name: "distmult"
out_dir: "out/kgc/kinship/graphsage_uni_ckpt"
model_type: 'graphsage'

vocab_lower_case: true

graph_construction_args:
  graph_construction_share:
    root_dir: 'examples/pytorch/kg_completion/kinship'
    topology_subdir: 'e1rel_to_e2'

  graph_construction_private:
    edge_strategy: null # None or "as_node"

  node_embedding:
    input_size: 300
    hidden_size: 300
    word_dropout: 0.2
    rnn_dropout: 0.3
    fix_bert_emb: false
    fix_word_emb: false
    embedding_style:
      single_token_item: false
      emb_strategy: "w2v_bilstm"
      num_rnn_layers: 1
      bert_model_name: null
      bert_lower_case: null

graph_embedding_args:
  graph_embedding_share:
    num_layers: 2
    hidden_size: 300
    direction_option: "undirected"

  graph_embedding_private:
    aggregator_type: "mean"

decoder_args:
