graph_construction_name: "triples"
graph_embedding_name: "gcn"
decoder_name: "stdrnn"
#out_dir: "out/webnlg1/gcn_bifuse_l2_wornn_wocopy_cover_glove_ckpt"
#out_dir: "out/webnlg1/gcn_bifuse_l2_wornn_wocopy_glove_ckpt"
out_dir: "out/webnlg1/gcn_bifuse_l2_wornn_glove_ckpt"
#out_dir: "out/webnlg1/gcn_bifuse_l2_glove_ckpt"
model_type: 'gcn'

vocab_lower_case: true

graph_construction_args:
  graph_construction_share:
    graph_type: 'triples'
    root_dir: 'examples/pytorch/rdf2text/data/webnlg1'
    topology_subdir: 'Triples_GMP1'
    thread_number: 4
    port: 9000
    timeout: 15000

  graph_construction_private:
    edge_strategy: 'homogeneous'
    merge_strategy: 'tailhead'
    sequential_link: true
    as_node: false

  node_embedding:
    input_size: 300
    hidden_size: 300
    word_dropout: 0.2
    rnn_dropout: 0.3
    fix_bert_emb: false
    fix_word_emb: false
    embedding_style:
      single_token_item: true
#      emb_strategy: "w2v"
      emb_strategy: "w2v_bilstm"
      num_rnn_layers: 1
      bert_model_name: null
      bert_lower_case: null

graph_embedding_args:
  graph_embedding_share:
    num_layers: 2
    input_size: 300
    hidden_size: 300
    output_size: 300
#    direction_option: "undirected"
    direction_option: "bi_fuse"
    feat_drop: 0.2

  graph_embedding_private:
    gcn_norm: 'both'
    weight: true
    bias: true
    activation: "relu"
    allow_zero_in_degree: false
    use_edge_weight: true

#  graph_embedding_private:
#    heads: [2, 2, 1]
#    attn_drop: 0.2
#    negative_slope: 0.2
#    residual: true
#    activation: null
#    activation: "relu"


decoder_args:
  rnn_decoder_share:
    rnn_type: "lstm"
    input_size: 300
    hidden_size: 512
    rnn_emb_input_size: 300
    use_copy: true
    use_coverage: false
    graph_pooling_strategy: "max"
#    graph_pooling_strategy: "mean"
#    attention_type: "uniform"
    attention_type: "sep_diff_encoder_type"
    fuse_strategy: "concatenate"
    dropout: 0.3

  rnn_decoder_private:
    max_decoder_step: 50
#    max_decoder_step: 80
    node_type_num: null
    tgt_emb_as_output_layer: true
#    tgt_emb_as_output_layer: false

# screen -S gcn python -m examples.pytorch.rdf2text.run_rdf2text -g2s_config examples/pytorch/rdf2text/config/webnlg1/gcn.yaml -task_config examples/pytorch/rdf2text/config/webnlg1/rdf2text.yaml