# Data
dataset: 'cnn'
pre_word_emb_file: null # path to the pretrained word embedding file
#pre_word_emb_file: '../glove/glove.6B.300d.txt' # path to the pretrained word embedding file

# Preprocessing
top_word_vocab: 70000
share_vocab: True
word_emb_size: 300
min_word_freq: 1
num_hidden: 300 # number of hidden units
n_samples: null


word_dropout: 0.4 # word embedding dropout
enc_rnn_dropout: 0.3 # Encoder RNN dropout
coverage_loss_ratio: 0.3 # coverage loss ratio


# Training
seed: 1234
batch_size: 50 # batch size
epochs: 100 # number of maximal training epochs
grad_clipping: 10
early_stop_metric: 'ROUGE'
patience: 10
lr: 0.0005 # learning rate
lr_patience: 2
lr_reduce_factor: 0.5
num_workers: 0 # number of data loader workers


# Beam search
beam_size: 15

gpu: -1
no_cuda: false

# fairseq-preprocess --source-lang "input" --target-lang "output" --trainpref $TEXT/train --validpref $TEXT/val --testpref $TEXT/test --destdir data-bin/cnn_pre

#"""
#CUDA_VISIBLE_DEVICES=2 fairseq-train data-bin/cnn_pre --optimizer adam --lr 0.005 --lr-shrink 0.5 --max-tokens 12000 --arch lstm_wiseman_iwslt_de_en --save-dir checkpoints/lstm"""