## Where the samples will be written
save_data: text_cnn/run/example
## Where the vocab(s) will be written
src_vocab: text_cnn/run/example.vocab.src
tgt_vocab: text_cnn/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# truncate examples
src_seq_length_trunc: 400
tgt_seq_length_trunc: 100

# common vocabulary for source and target
share_vocab: True

# Corpus opts:
data:
    text_cnn:
        path_src: text_cnn/train.input
        path_tgt: text_cnn/train.output
    valid:
        path_src: text_cnn/val.input
        path_tgt: text_cnn/val.output

# onmt_build_vocab -config config/onmt_cnn.yaml -n_sample -1