graph_type: 'node_emb'
root_dir: "graph4nlp/pytorch/test/dataset/jobs"
topology_subdir: 'NodeEmbGraph'
merge_strategy: 'tailhead'
dynamic_graph_type: 'node_emb'
sim_metric_type: "weighted_cosine"
num_heads: 1
epsilon_neigh: 0.5
smoothness_ratio: 0.1
connectivity_ratio: 0.05
sparsity_ratio: 0.1